version: "3.7"
services:
    app:
        build:
            args:
                user: oxygem
                uid: 1000
            context: ./
            dockerfile: docker/php.Dockerfile
        container_name: wsr-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            - traffic
    db:
        image: mysql:8.0.33
        restart: unless-stopped
        container_name: wsr-db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wsr
        volumes:
            - ./mysql-data:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        networks:
            - traffic
    nginx:
        image: nginx:alpine
        container_name: wsr-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - traffic
networks:
    traffic:
        driver: bridge